### ISSUE TITLE
Add an option to hide Tab Pane icons

### ISSUE THREAD

**Issue by KSXGitHub** [v3ss0n/steam-pirate-ui#5]

**Comment by KSXGitHub** [comment]
I added this code to my `styles.less` and fixed my problem

``` less
.tab .title {
  &:not(.icon)::before {
    content: "";
    display: none;
  }
}
```

But it still be cool if you accept this proposal, I guess I'm not the only one who is expecting this
